# Generated by Django 4.0.3 on 2022-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdFamilia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
